name: dartex
description: Experimental ECS written in Dart.
version: 0.0.5
homepage: https://github.com/DavidDomkar/dartex

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  test: ^1.12.0
