name: dartex
description: Experimental ECS written in Dart.
version: 0.1.6
homepage: https://github.com/DavidDomkar/dartex

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  collection: ^1.14.0

dev_dependencies:
  test: ^1.12.0
